site_name: detectEr Tutorial
site_description: A step-by-step guide to using detectEr
repo_url: https://github.com/duncanatt/detecter
repo_name: duncanatt/detecter
use_directory_urls: false
copyright: Copyright &copy; 2019 - 2021 Duncan Paul Attard

markdown_extensions:
  - def_list # Definition lists.
  - attr_list # Attribute lists.
  - abbr # Abbreviation definitions and hover help tooltip.
  - admonition # Admonitions.
  - smarty # Smarty pants.
  # - codehilite
  - footnotes
  - pymdownx.snippets # Insert content from other files.
  - pymdownx.superfences # Nestable code and content blocks inside admonitions.
  - pymdownx.highlight: # Block code syntax highlighting.
      code_attr_on_pre: true
  - pymdownx.inlinehilite # Inline code syntax highlighting.
  - pymdownx.smartsymbols
  - pymdownx.keys # Icon keyboard keys.
  - pymdownx.details # Collapsible admonitions.
  - pymdownx.tabbed # Tabs.
  - pymdownx.critic # Track changes.
  - pymdownx.caret # Superscripts.
  - pymdownx.tilde # Subscripts.
  - pymdownx.mark # Highlighting.
  - pymdownx.smartsymbols # Smart symbols such as (tm), (c), etc.
  - pymdownx.betterem: # Better support for bold and italicized text.
      smart_enable: all
  - pymdownx.arithmatex: # MathJax
      generic: true
  - pymdownx.emoji: # Icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
      # baselevel: 3
      # anchorlink: false
      # anchorlink_class: section-header 
      # toc_depth: 3

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6 # Polyfills.
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # Add MathJax

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros:
      include_dir: includes

extra:
  # font: false
  generator: true
  social:
    - icon: fontawesome/solid/user-circle
      link: https://duncanatt.github.io
      name: Profile
    - icon: fontawesome/brands/github
      link: https://github.com/duncanatt
      name: Duncan on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/duncanattard
      name: Duncan on Twitter
    - icon: fontawesome/solid/envelope-open
      link: mailto:duncanatt@gmail.com
      name: Drop a line
  benchmark:
    bin_dir: /Users/duncan/Dropbox/PhD/Development/detecter-private/ebin
    runs_dir: /Users/duncan/Dropbox/PhD/Development/detecter-private/runs
    plots_dir: /Users/duncan/Dropbox/PhD/Development/detecter-private/plots
    rep_cnt: 5
    sched_cnt: 16


theme:
  name: material

#  favicon: assets/logo.png

  palette:
    - scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Source Sans Pro
    code: Fira Code

  language: en

  features:
    - navigation.instant
#    - navigation.sections
    - navigation.top
    - header.autohide
#    - navigation.tabs
    - navigation.expand
    - toc.integrate

  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Preparation: getting-started/preparation.md
    - Setting up detectEr: getting-started/setting-up-detecter.md 
    - Quickstart: getting-started/quickstart.md
  - Using detectEr Branching Time:
    - Getting Started: using-detecter/getting-started.md
    - The Specification Logic: using-detecter/the-specification-logic.md
    - Formalising Properties: using-detecter/formalising-properties.md
    - Runtime Verification: using-detecter/runtime-verification.md
    - Synthesising Analysers: using-detecter/synthesising-analysers.md
    - Instrumentation: using-detecter/instrumentation.md
    - Inline Instrumentation: using-detecter/inline-instrumentation.md
    - Outline Instrumentation: using-detecter/outline-instrumentation.md
    - Offline Instrumentation: using-detecter/offline-instrumentation.md
  - Using detectEr Linear Time:
    - Setting up detectEr Linear Time: detecter-linear-time/setting-up-detecter.md
    - Getting Started: detecter-linear-time/getting-started.md
    - The Specification Logic: detecter-linear-time/the-specification-logic.md
    - Synthesising Analysers: detecter-linear-time/synthesising-analysers.md
    - Inline Instrumentation: detecter-linear-time/inline-instrumentation.md
    - Verdict Explainability: detecter-linear-time/verdict-explainability.md
