name: Build

on:
  #  schedule:
  #    - cron: '*/30 * * * *'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.1.5

    env:
      BIN: ebin
      INCLUDE: include
      SRC: src
      TEST: test

    steps:
#      - uses: actions/checkout@v1
#      - name: Run a one-line script
#        run: echo Hello, world! $SRC/*.erl $SRC/**/*.erl
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
      - name: Compile
        run: |
          rm -rf $BIN/*.beam erl_crash.dump
          mkdir -p $BIN
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $SRC/*.erl $SRC/**/*.erl
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $TEST/**/*.erl
      - name: Test
        run: |
          erl -noshell -pa ebin -eval 'eunit:test(log_tracer_test, [verbose])' -s init stop
          erl -noshell -pa ebin -eval 'eunit:test(async_tracer_test, [verbose])' -s init stop
