name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.1.5

    env:
      BIN: detecter/ebin
      INCLUDE: detecter/include
      SRC: detecter/src
      TEST: detecter/test

    steps:
      - uses: actions/checkout@v1
      - name: Compile
        run: |
          rm -rf $BIN/*.beam erl_crash.dump
          mkdir -p $BIN
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $SRC/*.erl $SRC/**/*.erl
          erlc -DTEST -pa $BIN +debug_info -I $INCLUDE -o $BIN $TEST/**/*.erl
      - name: List
        run: |
          ls -lart $BIN
      - name: Test
        run: |
          erl -noshell -pa $BIN -eval 'case eunit:test(log_tracer_test, [verbose]) of error -> init:stop(1); Result -> Result end.' -s init stop
          # The 'tracer_test' has been disabled until the timing issues have been fixed in every test.
          #erl -noshell -pa $BIN -eval 'case eunit:test(tracer_test, [verbose]) of error -> init:stop(1); Result -> Result end.' -s init stop
